export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_PRODUCT_DOWNLOAD = 'START_PRODUCT_DOWNLOAD';
export const PRODUCT_DOWNLOAD_SUCCESS = 'PRODUCT_DOWNLOAD_SUCCESS';
export const PRODUCT_DOWNLOAD_ERROR = 'PRODUCT_DOWNLOAD_ERROR';

export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR';

export const GET_PRODUCT_EDIT = 'GET_PRODUCT_EDIT';
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS';
export const PRODUCT_EDIT_ERROR = 'PRODUCT_EDIT_ERROR';